version: '2.27'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db_auth

  db_auth:
    container_name: db_auth
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=2281337
      - POSTGRES_USER=timur5050
    image: postgres:14.3-alpine