# Generated by Django 5.0.4 on 2024-05-03 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaurant'),
        ),
    ]
