# Generated by Django 5.0.4 on 2024-05-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_employee_id_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creating_date', models.DateTimeField(auto_now_add=True)),
                ('menu_items', models.JSONField()),
                ('id_restaurant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.restaurant')),
            ],
        ),
    ]
