# Generated by Django 5.0.4 on 2024-05-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_menu_id_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(blank=True, default='standard', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_restaurant',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, default='no', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(blank=True, default='name', max_length=255),
        ),
        migrations.AlterField(
            model_name='employee',
            name='vote_result',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
