# Generated by Django 5.0.4 on 2024-05-09 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_menu_name_alter_employee_id_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='id_restaurant',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_restaurant',
            field=models.ForeignKey(db_column='id_restaurant', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
