# Generated by Django 5.0.4 on 2024-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_id_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_restaurant',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
